kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-data
  labels:
    type: local
spec:
  storageClassName: generic
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/jenkins/data"